# Generated by Django 5.0.2 on 2025-12-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organizationapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='api_key',
        ),
    ]
