# Generated by Django 5.0.2 on 2026-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_organization_api_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationapikey',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_apikey_name_per_organization'),
        ),
    ]
