# Generated by Django 5.0.2 on 2026-02-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        ('users', '0003_remove_organization_api_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_campaign_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_reward_name_per_organization'),
        ),
    ]
