# Generated by Django 5.0.2 on 2025-12-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn', 'Earn Points'), ('spend', 'Spend Points'), ('expiration', 'Points Expiration')], max_length=20),
        ),
    ]
