# Generated by Django 5.0.2 on 2026-01-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_transaction_transaction_type'),
        ('users', '0003_remove_organization_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='loyalty_tra_created_ef4f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', '-created_at'], name='loyalty_tra_custome_8a62fe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='loyalty_tra_transac_2d61e5_idx'),
        ),
    ]
