# Generated by Django 5.0.2 on 2025-12-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_customer_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
