# Generated by Django 5.0.2 on 2025-12-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='reward_type',
            field=models.CharField(choices=[('multiplier', 'Multiplier (e.g. x2)'), ('bonus', 'Fixed Bonus (e.g. +100 points)')], default='multiplier', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='points_value',
            field=models.IntegerField(),
        ),
    ]
