# Generated by Django 5.0.2 on 2025-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_campaign_reward_type_campaign_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='points_value',
            field=models.PositiveIntegerField(),
        ),
    ]
